const brandConfig = [
  {
    title: "Latvenergo",
    searchNames: ["latvenergo"],
    accountName: "Latvenergo",
    brandFile: "./brandTweets/latvenergo.json",
    peopleTweets: "./peopleTweets/latvenergo.json",
  },
  {
    title: "Rimi",
    searchNames: ["rimi"],
    accountName: "RimiLatvija",
    brandFile: "./brandTweets/rimi.json",
    peopleTweets: "./peopleTweets/rimi.json",
  },
  {
    title: "Maxima",
    searchNames: ["maxima"],
    accountName: "maximaveikals",
    brandFile: "./brandTweets/maxima.json",
    peopleTweets: "./peopleTweets/maxima.json",
  },
  {
    title: "Swedbank",
    searchNames: ["swedbank"],
    accountName: "SwedbankLatvia",
    brandFile: "./brandTweets/swedbank.json",
    peopleTweets: "./peopleTweets/swedbank.json",
  },
  {
    title: "Latvijas Mobilais Telefons",
    searchNames: ["latvijas mobilais telefons", "lmt"],
    accountName: "mansLMT",
    brandFile: "./brandTweets/lmt.json",
    peopleTweets: "./peopleTweets/lmt.json",
  },
  {
    title: "TET",
    searchNames: ["tet"],
    accountName: "mans_tet",
    brandFile: "./brandTweets/tet.json",
    peopleTweets: "./peopleTweets/tet.json",
  },
  {
    title: "Latvijas gāze",
    searchNames: ["latvijas gāze"],
    accountName: "ASLatvijasGaze",
    brandFile: "./brandTweets/lg.json",
    peopleTweets: "./peopleTweets/lg.json",
  },
  {
    title: "Tele2",
    searchNames: ["tele2"],
    accountName: "Tele2Latvia",
    brandFile: "./brandTweets/tele2.json",
    peopleTweets: "./peopleTweets/tele2.json",
  },
  {
    title: "Air Baltic Corporation",
    searchNames: ["air baltic"],
    accountName: "airBaltic",
    brandFile: "./brandTweets/airbaltic.json",
    peopleTweets: "./peopleTweets/airbaltic.json",
  },
  {
    title: "Olympic Casino",
    searchNames: ["olympic casino", "olympic"],
    accountName: "OCasino",
    brandFile: "./brandTweets/olympic.json",
    peopleTweets: "./peopleTweets/olympic.json",
  },
  {
    title: "SEB Banka",
    searchNames: ["seb banka", "seb"],
    accountName: "SEB_Latvia",
    brandFile: "./brandTweets/seb.json",
    peopleTweets: "./peopleTweets/seb.json",
  },
  {
    title: "Grindeks",
    searchNames: ["grindeks"],
    accountName: "AS_Grindeks",
    brandFile: "./brandTweets/grindeks.json",
    peopleTweets: "./peopleTweets/grindeks.json",
  },
  {
    title: "Citadele Banka",
    searchNames: ["citadele banka", "citadele"],
    accountName: "Citadele",
    brandFile: "./brandTweets/citadele.json",
    peopleTweets: "./peopleTweets/citadele.json",
  },
  {
    title: "Bite",
    searchNames: ["bite"],
    accountName: "Bitelv",
    brandFile: "./brandTweets/bite.json",
    peopleTweets: "./peopleTweets/bite.json",
  },
  {
    title: "Drogas",
    searchNames: ["drogas"],
    accountName: "DrogasLatvija",
    brandFile: "./brandTweets/drogas.json",
    peopleTweets: "./peopleTweets/drogas.json",
  },
  {
    title: "Depo DIY",
    searchNames: ["depo"],
    brandFile: "./brandTweets/depo.json",
    peopleTweets: "./peopleTweets/depo.json",
  },
  {
    title: "Cirkle K",
    searchNames: ["circle k"],
    accountName: "CircleKLatvija",
    brandFile: "./brandTweets/circlek.json",
    peopleTweets: "./peopleTweets/circlek.json",
  },
  {
    title: "Latvijas Balzams",
    searchNames: ["latvijas balzams"],
    accountName: "LBveikali",
    brandFile: "./brandTweets/lb.json",
    peopleTweets: "./peopleTweets/lb.json",
  },
  {
    title: "Optibet",
    searchNames: ["optibet"],
    accountName: "OptibetLatvija",
    brandFile: "./brandTweets/optibet.json",
    peopleTweets: "./peopleTweets/optibet.json",
  },
  {
    title: "Evolution",
    searchNames: ["evolution latvia", "evolution", "evolution gaming"],
    brandFile: "./brandTweets/evolution.json",
    peopleTweets: "./peopleTweets/evolution.json",
  },
];

module.exports = { brandConfig };
